*Download and import the Data Science Job Salary dataset.*

In [3]:
import pandas as pd
df = pd.read_csv('datascience_salaries.csv')
df.head()

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary
0,0,Data scientist,Full Time,Senior,New York City,USD,149000
1,2,Data scientist,Full Time,Senior,Boston,USD,120000
2,3,Data scientist,Full Time,Senior,London,USD,68000
3,4,Data scientist,Full Time,Senior,Boston,USD,120000
4,5,Data scientist,Full Time,Senior,New York City,USD,149000

*Normalize the 'salary' column using Min-Max normalization which scales all salary values between 0 and 1.*

In [4]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df['salary_norma'] = scaler.fit_transform(df[['salary']])
df['salary_norma'].describe()

count    1171.000000
mean        0.175940
std         0.164403
min         0.000000
25%         0.075758
50%         0.166667
75%         0.191919
max         1.000000
Name: salary_norma, dtype: float64

*Implement dimensionality reduction like Principal Component Analysis (PCA) or t-SNE to reduce the number of features (columns) in the dataset.*

In [3]:
# from sklearn.preprocessing import MinMaxScaler
# from sklearn.preprocessing import StandardScaler
# from sklearn.decomposition import PCA
# from sklearn.manifold import TSNE

# scaler = MinMaxScaler()
# df['salary'] = scaler.fit_transform(df[['salary']])
# df['salary']

# # # Scale features before PCA/t-SNE (important for fair comparison)
# std_scaler = StandardScaler()
# X_scaled = std_scaler.fit_transform(df.select_dtypes(include=['float64', 'int64'])
# )

# # # PCA ---
# pca = PCA(n_components=2)
# df_pca = pca.fit_transform(X_scaled)
# df_pca = pd.DataFrame(df_pca, columns=['PC1', 'PC2'])

# #  t-SNE ---
# tsne = TSNE(n_components=2, random_state=42)
# df_tsne = tsne.fit_transform(X_scaled)
# df_tsne = pd.DataFrame(df_tsne, columns=['TSNE1', 'TSNE2'])

#df_pca

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE


# Drop target column (salary) and keep only numeric features
X = df.drop('salary', axis=1).select_dtypes(include=['float64', 'int64'])

# Scale features before PCA/t-SNE (important for fair comparison)
std_scaler = StandardScaler()
X_scaled = std_scaler.fit_transform(X)

# PCA ---
pca = PCA(n_components=2)
df_pca = pca.fit_transform(X_scaled)
df_pca = pd.DataFrame(df_pca, columns=['PC1', 'PC2'])

#  t-SNE ---
tsne = TSNE(n_components=2, random_state=42)
df_tsne = tsne.fit_transform(X_scaled)
df_tsne = pd.DataFrame(df_tsne, columns=['TSNE1', 'TSNE2'])

Group the dataset by the 'experience_level' column and calculate the average and median salary for each experience level (e.g., Junior, Mid-level, Senior)

In [11]:
X_grouped = df.groupby('experience_level')

df_grouped_stats = X_grouped['salary'].agg(['mean', 'median', 'max', 'min'])

print(df_grouped_stats)

                          mean   median     max    min
experience_level
Entry             36111.111111  30000.0  140000  30000
Executive         76076.923077  46000.0  175000  41000
Mid               51786.885246  51000.0  160000  30000
Senior            75088.033012  68000.0  228000  30000